### ISSUE TITLE
Looks great! Scroll issue

### ISSUE THREAD

**Issue by nathanhleung** [ygaitonde/jupiter-recipe-extension#1]
Hi Yash -- this looks great! One quick question, when I add a recipe via URL (for example this one: https://tasty.co/recipe/5-ingredient-cauliflower-mac-n-cheese) and the recipe ingredients cover the rest of the extension window, I can't scroll down to click the "Create Recipe" button. Are you seeing the same thing on your end?

**Comment by ygaitonde** [comment]
Hey Nate. I did a fresh install of the extension by cloning my repo and tested in Firefox and Chrome and was unable to recreate the issue. I am attaching a gif of what the recipe load process looks like on my end. Let me know if you're still facing this issue or if you have any more information that may help me recreate the issue.

![jupiter-extension-recipe-load](https://user-images.githubusercontent.com/54426809/90419048-f9880500-e083-11ea-8814-fb1c981fe457.gif)

**Comment by nathanhleung** [comment]
Hi Yash, thanks for the gif! Here's what I see on my end:

https://www.youtube.com/watch?v=O_PJG-sLuXU

macOS Catalina 10.15.6
Chrome 84.0.4147.125 (Official Build) (64-bit)

Are you on Windows? Could it be an OS thing?

**Comment by ygaitonde** [comment]
I'm on MacOS version 10.15.5. I'm also on Chrome Version 84.0.4147.125 (Official Build) (64-bit).

I'm going to look into if there's something in Chrome Settings that you can adjust to fix the scrolling bug. In the meantime, maybe try using the extension in Firefox?

**Comment by ygaitonde** [comment]
I think my most recent PR solved this problem -- can you confirm?
